### ISSUE TITLE
Guzzle Requirement

### ISSUE THREAD

**Issue by intrepidws** [ghassani/surveymonkey-v3-api-php#14]
Does this package need Guzzle 6.2.2 specifically for some reason?

**Comment by ghassani** [comment]
Honestly I do not remember. May have just been the current version at the time. It should be ok with previous versions of 6.x, but guzzle API changes a lot from the major versions. I have not tested with anything lower than 6.2.2. What version are you trying to use it with?

**Comment by intrepidws** [comment]
I meant more like, why not allow versions higher than 6.2.2? I the current (6.3) and it seems to work fine.

**Comment by ghassani** [comment]
Set requirement to 6.*@stable in commit 3e6ab72
