### ISSUE TITLE
Not compatible with guzzlehttp/guzzle 6.4 

### ISSUE THREAD

**Issue by laelem** [ghassani/surveymonkey-v3-api-php#27]
Hello ! 
On the last tag (1.0.2), the method `src/Api/ResponsesTrait.php::getSurveyResponse` doesn't work anymore since i upgraded package `guzzlehttp/guzzle` from 6.2 to 6.4 (this exception is thrown : "Header value can not be an empty array.").
It's working fine on master though, so can you make a tag please ? (i have to set a commit in composer now)

**Comment by ken-mills** [comment]
I had the same problem recently. My workaround was to pull in a specific commit.
`"ghassani/surveymonkey-v3-api-php": "dev-master#9a5e851"`

See this article [stackoverflow issue](https://stackoverflow.com/questions/21314381/how-to-correctly-require-a-specific-commit-in-composer-so-that-it-would-be-avail).

This worked for me until Gassan has time to tag.

**Comment by ghassani** [comment]
I have incremented the version numbers and tagged master to 1.1.0
